<?php

namespace AppBundle\Repository;

/**
 * pizzasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class flowersRepository extends \Doctrine\ORM\EntityRepository
{
}
