<?php

namespace AppBundle\Repository;

/**
 * UserAdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAdressRepository extends \Doctrine\ORM\EntityRepository
{
}
