<?php

namespace AppBundle\Repository;

/**
 * VestigingenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VestigingenRepository extends \Doctrine\ORM\EntityRepository
{
}
